apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  name: SatyaKumar_Surisetti

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: greetings-app
  template:
    metadata:
      labels:
        app: greetings-app
    spec:
      containers:
      - name: greetings-app
        image: satyataskacr.azurecr.io/greetingsapp:v1
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis"  
        - name: REDIS_PORT
          value: "6379"  
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: name
        ports:
        - containerPort: 5000
      nodeSelector:
        app: greetings-app
      imagePullSecrets:
      - name: satyataskacr-credentials
       

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        app: redis-app
      containers:
      - name: redis-container
        image: redis:latest
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: azurefront-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: greetings-app
